# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Login_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(345, 129)
        self.gridLayout = QtWidgets.QGridLayout(Widget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_account = QtWidgets.QLabel(Widget)
        self.label_account.setObjectName("label_account")
        self.gridLayout.addWidget(self.label_account, 0, 0, 1, 1)
        self.lineEdit_account = QtWidgets.QLineEdit(Widget)
        self.lineEdit_account.setObjectName("lineEdit_account")
        self.gridLayout.addWidget(self.lineEdit_account, 0, 1, 1, 2)
        self.label_password = QtWidgets.QLabel(Widget)
        self.label_password.setObjectName("label_password")
        self.gridLayout.addWidget(self.label_password, 1, 0, 1, 1)
        self.lineEdit_password = QtWidgets.QLineEdit(Widget)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.gridLayout.addWidget(self.lineEdit_password, 1, 1, 1, 2)
        self.pushButton_signin = QtWidgets.QPushButton(Widget)
        self.pushButton_signin.setObjectName("pushButton_signin")
        self.gridLayout.addWidget(self.pushButton_signin, 2, 2, 1, 1)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label_account.setText(_translate("Widget", "帳號"))
        self.label_password.setText(_translate("Widget", "密碼"))
        self.pushButton_signin.setText(_translate("Widget", "登入"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Login_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
