# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(386, 133)
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_signin = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_signin.setGeometry(QtCore.QRect(261, 95, 105, 24))
        self.pushButton_signin.setObjectName("pushButton_signin")
        self.label_account = QtWidgets.QLabel(self.centralwidget)
        self.label_account.setGeometry(QtCore.QRect(39, 25, 105, 21))
        self.label_account.setObjectName("label_account")
        self.lineEdit_account = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_account.setGeometry(QtCore.QRect(150, 25, 216, 21))
        self.lineEdit_account.setObjectName("lineEdit_account")
        self.label_password = QtWidgets.QLabel(self.centralwidget)
        self.label_password.setGeometry(QtCore.QRect(39, 60, 105, 21))
        self.label_password.setObjectName("label_password")
        self.lineEdit_password = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_password.setGeometry(QtCore.QRect(150, 60, 216, 21))
        self.lineEdit_password.setObjectName("lineEdit_password")
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.pushButton_signin.setText(_translate("Login", "登入"))
        self.label_account.setText(_translate("Login", "帳號"))
        self.label_password.setText(_translate("Login", "密碼"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
