# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Mainchk.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mainchk(object):
    def setupUi(self, Mainchk):
        Mainchk.setObjectName("Mainchk")
        Mainchk.resize(547, 256)
        self.centralwidget = QtWidgets.QWidget(Mainchk)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Time_edit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.Time_edit.setObjectName("Time_edit")
        self.verticalLayout_2.addWidget(self.Time_edit)
        self.gb_country = QtWidgets.QGroupBox(self.centralwidget)
        self.gb_country.setObjectName("gb_country")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gb_country)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.But_kor = QtWidgets.QPushButton(self.gb_country)
        self.But_kor.setObjectName("But_kor")
        self.verticalLayout.addWidget(self.But_kor)
        self.But_jpn = QtWidgets.QPushButton(self.gb_country)
        self.But_jpn.setObjectName("But_jpn")
        self.verticalLayout.addWidget(self.But_jpn)
        self.But_hkg = QtWidgets.QPushButton(self.gb_country)
        self.But_hkg.setObjectName("But_hkg")
        self.verticalLayout.addWidget(self.But_hkg)
        self.But_chn = QtWidgets.QPushButton(self.gb_country)
        self.But_chn.setObjectName("But_chn")
        self.verticalLayout.addWidget(self.But_chn)
        self.But_twn = QtWidgets.QPushButton(self.gb_country)
        self.But_twn.setObjectName("But_twn")
        self.verticalLayout.addWidget(self.But_twn)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2.addWidget(self.gb_country)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.chk_tb = QtWidgets.QTableWidget(self.centralwidget)
        self.chk_tb.setRowCount(20)
        self.chk_tb.setObjectName("chk_tb")
        self.chk_tb.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        item.setFont(font)
        self.chk_tb.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        item.setFont(font)
        self.chk_tb.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        item.setFont(font)
        self.chk_tb.setHorizontalHeaderItem(2, item)
        self.chk_tb.horizontalHeader().setCascadingSectionResizes(True)
        self.chk_tb.horizontalHeader().setMinimumSectionSize(31)
        self.chk_tb.horizontalHeader().setStretchLastSection(False)
        self.chk_tb.verticalHeader().setCascadingSectionResizes(False)
        self.horizontalLayout.addWidget(self.chk_tb)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        Mainchk.setCentralWidget(self.centralwidget)

        self.retranslateUi(Mainchk)
        QtCore.QMetaObject.connectSlotsByName(Mainchk)

    def retranslateUi(self, Mainchk):
        _translate = QtCore.QCoreApplication.translate
        Mainchk.setWindowTitle(_translate("Mainchk", "MainWindow"))
        self.gb_country.setTitle(_translate("Mainchk", "國家"))
        self.But_kor.setText(_translate("Mainchk", "台灣"))
        self.But_jpn.setText(_translate("Mainchk", "中國"))
        self.But_hkg.setText(_translate("Mainchk", "香港"))
        self.But_chn.setText(_translate("Mainchk", "日本"))
        self.But_twn.setText(_translate("Mainchk", "韓國"))
        item = self.chk_tb.horizontalHeaderItem(0)
        item.setText(_translate("Mainchk", "產品"))
        item = self.chk_tb.horizontalHeaderItem(1)
        item.setText(_translate("Mainchk", "排程"))
        item = self.chk_tb.horizontalHeaderItem(2)
        item.setText(_translate("Mainchk", "檢查"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Mainchk = QtWidgets.QMainWindow()
    ui = Ui_Mainchk()
    ui.setupUi(Mainchk)
    Mainchk.show()
    sys.exit(app.exec_())
